# Generated by Django 4.2.3 on 2023-08-17 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_image_alter_likes_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={'ordering': ('user', 'blog', 'likes')},
        ),
    ]
