# Generated by Django 4.2.3 on 2023-08-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_likes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likes',
            options={},
        ),
    ]
